<a href="https://colab.research.google.com/github/ClaudiaTurner/GEOG5990M/blob/main/Final_Project_Python_GEOG5990M.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# GEOG5990M Final Assignment (Template)

Student ID number:

In [ ]:
# read in required packages

This is an example block of mardown text I want to reference <a href="#ref1">[1]</a>. I might need to add some more citations <a href="#ref2">[2]</a><a href="#ref2">[3]</a>

Data Visualisation
- Don't forget to present your final two data visualisation (one spatial and one non-spatial) and the justifications about the decisions you made whilst preparing and visualising the data.

In [ ]:
import pandas as pd
# import geopandas as gpd
# import matplotlib.pyplot as plt

In [ ]:
Sales_England=pd.read_csv('https://github.com/ClaudiaTurner/GEOG5990M/raw/main/Sales_1995_2023_England_Districts_exp.csv')

In [32]:
Sales_England.head(50)

,Residential property sales,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30
0,ONS Crown Copyright Reserved [from Nomis on 8 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Count of sales:,Sales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,row,Sep-96,Sep-97,Sep-98,Sep-99,Sep-00,Sep-01,Sep-02,Sep-03,Sep-04,...,Sep-16,Sep-17,Sep-18,Sep-19,Sep-20,Sep-21,Sep-22,Sep-23,Area,mnemonic
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1,850013,1047268,1016037,1084672,1130983,1133620,1271168,1153345,1264229,...,903005,852771,829715,803012,669410,1081660,787290,573646,country:England,E92000001
6,2,1159,1390,1405,1440,1726,2140,2359,2488,2979,...,1273,1209,1304,1235,1050,1729,1490,1103,ladu2023:Hartlepool,E06000001
7,3,1776,1934,1948,2055,2280,2462,2826,3016,3339,...,1822,1749,1819,1828,1528,2316,2035,1298,ladu2023:Middlesbrough,E06000002
8,4,1879,2000,1957,1986,2266,2582,3497,3390,3138,...,1824,1947,2007,1967,1636,2539,2081,1667,ladu2023:Redcar and Cleveland,E06000003
9,5,2670,3331,3305,3291,3978,4168,5320,4610,4471,...,2922,2959,3090,3066,2523,3826,3063,2186,ladu2023:Stockton-on-Tees,E06000004
10,6,1828,2178,2095,2179,2538,2770,3033,2926,3288,...,1679,1642,1602,1616,1501,2435,1885,1339,ladu2023:Darlington,E06000005
11,7,7008,7890,8267,8134,8802,9579,11461,11793,12493,...,7618,7816,7917,7789,6459,10009,8389,6272,ladu2023:County Durham,E06000047
12,8,4655,5568,5510,5686,6370,6705,7456,7317,7442,...,5334,5459,5498,5378,4595,7061,5585,4014,ladu2023:Northumberland,E06000057
13,9,3606,4666,4606,4587,4884,5371,5983,5825,6071,...,3885,3911,3676,3612,3206,4886,4029,2890,ladu2023:Newcastle upon Tyne,E08000021
14,10,3270,3895,4013,4307,4697,4714,4947,5193,5307,...,3464,3615,3722,3495,2834,4160,3089,2605,ladu2023:North Tyneside,E08000022
15,11,1711,1902,1979,1859,2168,2241,2672,2690,2946,...,1835,1813,1754,1818,1477,2235,1860,1361,ladu2023:South Tyneside,E08000023
16,12,3211,3613,3910,4204,4470,4478,5304,5680,6259,...,3281,3455,3427,3489,2901,4351,3787,2644,ladu2023:Sunderland,E08000024
17,13,2569,2773,3009,3115,3198,3442,4078,4417,4805,...,2622,2658,2644,2511,2170,3206,2791,2101,ladu2023:Gateshead,E08000037
18,14,1374,1299,1473,1712,2242,1919,2408,2677,2804,...,1765,1839,1774,1659,1401,1800,1535,1146,ladu2023:Halton,E06000006
19,15,3434,4040,3882,3819,3897,3896,4497,4580,4754,...,3482,3187,3041,3089,2695,4295,2960,2284,ladu2023:Warrington,E06000007
20,16,2429,2723,2569,2623,2689,3036,3408,3424,4014,...,1693,1707,1827,1897,1590,2340,2020,1405,ladu2023:Blackburn with Darwen,E06000008
21,17,2512,3047,3217,3200,3606,3987,5026,4775,4966,...,2034,2004,2080,2138,1726,2600,2608,1826,ladu2023:Blackpool,E06000009
22,18,6011,7812,7717,7812,9173,8916,10279,9417,9894,...,7542,7534,7480,7695,6593,10481,7311,5310,ladu2023:Cheshire East,E06000049
23,19,5012,5800,5779,6539,7411,7028,8068,7586,7939,...,6325,6383,6175,5976,4641,7714,5644,4172,ladu2023:Cheshire West and Chester,E06000050
24,20,4228,4500,4440,4799,5100,5450,6260,6291,6411,...,4574,4463,4739,4598,3855,6255,4837,3467,ladu2023:Cumberland,E06000063
25,21,3836,4863,4899,5279,5438,5299,5879,5706,5783,...,4092,4264,4055,4092,3329,5623,3975,2997,ladu2023:Westmorland and Furness,E06000064
26,22,1479,1292,1924,1660,1847,2296,2659,3370,3575,...,1430,1551,1548,1406,1228,1801,1622,1161,ladu2023:Burnley,E07000117
27,23,1468,1957,2009,2092,2372,2400,2875,2668,2886,...,2132,2087,2121,2016,1705,2448,1819,1261,ladu2023:Chorley,E07000118
28,24,1330,1929,1783,1830,1994,2100,2404,2209,2340,...,1729,1748,1617,1611,1334,2202,1694,1104,ladu2023:Fylde,E07000119
29,25,1468,1690,1549,1487,1673,1952,2164,2547,2669,...,1264,1211,1171,1244,1076,1485,1323,898,ladu2023:Hyndburn,E07000120
30,26,2207,2742,2633,2418,3333,3495,4232,3995,3978,...,2383,2510,2420,2436,1852,2987,2219,1686,ladu2023:Lancaster,E07000121
31,27,1355,1288,1737,1826,1892,2154,2592,2519,3236,...,1538,1384,1468,1487,1248,1847,1486,1096,ladu2023:Pendle,E07000122
32,28,2219,2611,2507,2323,2689,2854,3533,3176,3474,...,1862,2017,2011,2027,1725,2568,2248,1465,ladu2023:Preston,E07000123
33,29,976,1318,1208,1060,1216,1323,1537,1436,1464,...,1025,1215,1092,1146,1069,1657,1127,767,ladu2023:Ribble Valley,E07000124
34,30,732,907,1336,1271,1280,1405,1791,1598,2219,...,1235,1282,1201,1185,980,1431,1210,791,ladu2023:Rossendale,E07000125
35,31,1798,2077,2160,1964,2393,2376,2966,2677,2852,...,1877,1917,1867,1929,1644,2574,1973,1405,ladu2023:South Ribble,E07000126
36,32,1193,1691,1742,1866,2073,2095,2391,2263,2527,...,1537,1478,1502,1661,1395,2261,1609,1168,ladu2023:West Lancashire,E07000127
37,33,2017,2315,2258,2485,2723,2855,3315,2836,2922,...,1927,1967,1987,1958,1764,3052,2181,1392,ladu2023:Wyre,E07000128
38,34,4169,4695,4508,4698,4792,5613,6707,6259,6447,...,4056,3940,3901,3831,3240,4750,3704,2802,ladu2023:Bolton,E08000001
39,35,2904,3312,3438,3664,4009,3953,4671,4570,5071,...,3166,2996,2954,2780,2149,3345,2592,1984,ladu2023:Bury,E08000002
40,36,5077,5991,6150,7161,8640,8814,11011,12119,13370,...,7436,6872,6343,5868,5130,6805,5588,3747,ladu2023:Manchester,E08000003
41,37,3347,3693,3755,3973,4084,4116,4681,4816,5109,...,2688,2976,2884,2780,2490,3311,2666,1965,ladu2023:Oldham,E08000004
42,38,2669,2884,2971,3405,3731,3888,4344,4052,4131,...,2841,2850,2959,2965,2471,3392,2911,2003,ladu2023:Rochdale,E08000005
43,39,2747,3391,3241,3561,3896,4026,4852,5369,6073,...,5084,4713,4650,4551,3335,4944,3880,2565,ladu2023:Salford,E08000006
44,40,4392,5623,5799,6165,6504,6015,6686,6225,6654,...,5276,5068,4991,4789,4015,6288,4290,3414,ladu2023:Stockport,E08000007
45,41,3257,3617,3512,3580,4247,4264,4931,4859,4923,...,3179,3312,3408,3209,2589,3950,3035,2320,ladu2023:Tameside,E08000008
46,42,3499,4375,3958,4415,4412,4142,5007,4973,5555,...,3994,3727,3838,3540,2768,5119,3053,2336,ladu2023:Trafford,E08000009
47,43,4601,5293,5319,5001,5592,5929,6835,6889,7175,...,4681,4905,5146,5342,4538,6097,5008,3446,ladu2023:Wigan,E08000010
48,44,1890,1988,1881,2022,2259,2016,2348,2598,2759,...,1728,1835,1964,2197,1831,2345,1867,1413,ladu2023:Knowsley,E08000011
49,45,5670,6118,6214,6488,6862,6864,8232,9845,10662,...,6154,6764,6841,6582,4858,6244,5416,4129,ladu2023:Liverpool,E08000012

In [37]:
Sales_England.isnull().sum()

Residential property sales    2
Unnamed: 1                    3
Unnamed: 2                    4
Unnamed: 3                    4
Unnamed: 4                    4
Unnamed: 5                    4
Unnamed: 6                    4
Unnamed: 7                    4
Unnamed: 8                    4
Unnamed: 9                    4
Unnamed: 10                   4
Unnamed: 11                   4
Unnamed: 12                   4
Unnamed: 13                   4
Unnamed: 14                   4
Unnamed: 15                   4
Unnamed: 16                   4
Unnamed: 17                   4
Unnamed: 18                   4
Unnamed: 19                   4
Unnamed: 20                   4
Unnamed: 21                   4
Unnamed: 22                   4
Unnamed: 23                   4
Unnamed: 24                   4
Unnamed: 25                   4
Unnamed: 26                   4
Unnamed: 27                   4
Unnamed: 28                   4
Unnamed: 29                   4
Unnamed: 30                   4
dtype: int64

## References
<p><a href="add_url_here">[1]</a>Footnote citation goes here</p>
<p><a href="https://github.com/FrancescaPontin/GEOG5990">[2]</a>GEOG5990M course materials</p>
<p><a href="add_url_here">[3]</a>Citation 3</p>